# Enable or disable LiveReload (enabled by default)
spring.devtools.livereload.enabled=true
# Disable restart feature (enabled by default)
spring.devtools.restart.enabled=true

appdata-path=src/main/resources/lists/

#Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false
spring.web.resources.static-locations=file:src/main/resources/static/
spring.web.resources.chain.cache=false
spring.web.resources.cache.period=0

# Enable hot reloading of static assets
spring.web.resources.static-locations[0]=file:src/main/resources/static/css/
spring.web.resources.static-locations[2]=file:src/main/resources/static/js/
spring.web.resources.static-locations[1]=classpath:/static/
spring.web.resources.static-locations[3]=classpath:/static/css/

# Watch additional directories
spring.devtools.restart.additional-paths=src/main/resources,src/main/resources/docs