# ===== OFFICIAL PROPERTIES ======
spring.application.name=Imperium
logging.level.root=INFO
server.port=3000
spring.security.user.name=yourUsername
spring.security.user.password=yourPassword

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# ===== CUSTOM PROPERTIES ======
# Landing page defaults
landing-page.list=todolist
landing-page.view=To-Do

# Paths
paths.appdata=/appdata/
paths.list-view=${paths.appdata}/listviews
paths.filter-sets=${paths.appdata}/filters/filterSets.yaml
paths.favicon=favicon.ico