spring.application.name=Imperium
logging.level.root=INFO

# Landing page defaults
landing-page.list=todolist
landing-page.view=To-Do

# Root app data path for accessing all files for lists, views, filters, etc.
appdata-path=/appdata/

# Specific paths relative to the app-data path
list-views-path=${appdata-path}/listviews
filterSets.filePath=${appdata-path}/filters/filterSets.yaml

server.port=3000
spring.security.user.name=yourUsername
spring.security.user.password=yourPassword

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*